### ISSUE TITLE
编辑页-人物列表、背景、素材列表，滚动条太丑了

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#126]
![Uploading image.png…]()

**Comment by dorislike1** [comment]
这个放最后吧，默认的滚动条还好吧

**Comment by four2024** [comment]
<img width="617" alt="image" src="https://github.com/psyai-net/webAppbug/assets/143800634/de4ebd0d-9c65-40e5-b389-6861eca9470a">

**Comment by four2024** [comment]
<img width="223" alt="image" src="https://github.com/psyai-net/webAppbug/assets/143800634/3d387b45-b902-453d-8ae8-9a22f15fcf45">
