### ISSUE TITLE
toast提示有很多个

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#127]
![Uploading image.png…]()

**Comment by xuyao0916** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/92b1f32c-cd10-4d45-90cb-a7dc7f231293)

**Comment by dorislike1** [comment]
你一直点，一直有toast,房子看看这个交互

**Comment by fangxiuq** [comment]
当前先放一放，后面进行整体优化
