### ISSUE TITLE
生成视频时一直在转圈圈 好几天都不失败

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#132]
![Uploading image.png…]()

**Comment by dorislike1** [comment]
如果还有问题，然陈龚看看

**Comment by xuyao0916** [comment]
这个在编辑页关闭浏览器和使用浏览器返回还是会存在这个问题

**Comment by dorislike1** [comment]
房子看看

**Comment by fangxiuq** [comment]
![screenshot-20240410-155858](https://github.com/psyai-net/webAppbug/assets/35586227/65f3bcd5-f509-4add-8eac-d23d6b3c43b2)
手机号：13301168460，production id：36，出现同样问题
