### ISSUE TITLE
AI生成内容-输入内容后登录账号内容被清空

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#159]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/83a80169-ba18-4ddc-a45b-a9cd0cb2e6b9)

**Comment by dorislike1** [comment]
放二期给交互

**Comment by dorislike1** [comment]
这个是优化项，

**Comment by fangxiuq** [comment]
这个一期可以先不用处理，后续优化，我在one-app中新建了一个issue：https://github.com/psyai-net/one-app/issues/705
