### ISSUE TITLE
我的订单-未支付的订单没有取消按钮

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#162]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/778b3a0e-89d3-40c3-bdf4-446f6a33fb8a)

**Comment by dorislike1** [comment]
没有接口

**Comment by ytrjp** [comment]
第一步，查询订单，订单状态为created
![img_v3_029e_e49b3dc9-298a-478c-b22b-82d68575f31g](https://github.com/psyai-net/webAppbug/assets/1198711/10aaeee7-1a83-4b05-96a0-5f9343d0d550)

第二步，update订单
curl -X 'POST' \
  'https://auth-test.psyai.net/api/update-payment?id=psyai%2Fpayment_20240328_092613_5708749' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "createdTime": "2024-03-28T09:26:13Z",
  "currency": "CNY",
  "detail": "",
  "displayName": "payment_20240328_092613_5708749",
  "invoiceRemark": "",
  "invoiceTaxId": "",
  "invoiceTitle": "",
  "invoiceType": "",
  "invoiceUrl": "",
  "message": "",
  "name": "payment_20240328_092613_5708749",
  "outOrderId": "payment_20240328_092613_5708749",
  "owner": "psyai",
  "payUrl": "weixin://wxpay/bizpayurl?pr=HgQHyYKzz",
  "personEmail": "",
  "personIdCard": "",
  "personName": "",
  "personPhone": "",
  "price": 1980,
  "productDisplayName": "年会员",
  "productName": "year_vip",
  "provider": "provider_payment-wechat",
  "returnUrl": "",
  "state": "Paid",
  "successUrl": "https://auth-test.psyai.net/payments/psyai/payment_20240328_092613_5708749/result",
  "tag": "Casdoor Summit 2022",
  "type": "WeChat Pay",
  "user": "xuyao111"
}
'
![img_v3_029e_3357b6ba-1151-4443-90b8-9b149cc2683g](https://github.com/psyai-net/webAppbug/assets/1198711/722430f8-a6e7-44f0-bb19-88aaec07d297)


第三步，查询。状态已变更
![Uploading img_v3_029e_a3dc9bce-edcf-4c28-94f2-8fef07f4b40g.jpg…]()

**Comment by ytrjp** [comment]
![img_v3_029e_a3dc9bce-edcf-4c28-94f2-8fef07f4b40g](https://github.com/psyai-net/webAppbug/assets/1198711/b0c8caed-9f27-4131-b33b-717fc793cdce)

**Comment by ytrjp** [comment]
1. 查询 psyai/payment_20240319_174757_1dc9eb2  curl -X 'GET' \
  'https://auth-test.psyai.net/api/get-payment?id=psyai%2Fpayment_20240319_174757_1dc9eb2' \
  -H 'accept: application/json'
2. notify API curl -X 'POST' \
  'https://auth-test.psyai.net/api/notify-payment/psyai/payment_20240319_152146_d9c3967' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '
  {
     "owner": "psyai",
    "name": "payment_20240319_152146_d9c3967",
    "createdTime": "2024-03-19T15:21:46Z",
    "displayName": "payment_20240319_152146_d9c3967",
    "provider": "provider_payment-wechat",
    "type": "WeChat Pay",
    "productName": "month_vip",
    "productDisplayName": "月会员",
    "detail": "",
    "tag": "Casdoor Summit 2022",
    "currency": "CNY",
    "price": 0.01,
    "returnUrl": "",
    "user": "string",
    "personName": "",
    "personIdCard": "",
    "personEmail": "",
    "personPhone": "",
    "invoiceType": "",
    "invoiceTitle": "",
    "invoiceTaxId": "",
    "invoiceRemark": "",
    "invoiceUrl": "",
    "outOrderId": "payment_20240319_152146_d9c3967",
    "payUrl": "weixin://wxpay/bizpayurl?pr=wZFqcWBzz",
    "successUrl": "https://auth-test.psyai.net/payments/psyai/payment_20240319_152146_d9c3967/result",
    "state": "Canceled",
    "message": ""
}
'
3. 查询 
![image](https://github.com/psyai-net/webAppbug/assets/1198711/7790f841-0001-4ee8-846e-869280588316)

**Comment by dorislike1** [comment]
这个接口也不行

**Comment by ytrjp** [comment]
已完成取消功能，取消成功后，需要将数据进行刷新操作
