### ISSUE TITLE
订单页-我的订单未支付订单，没有倒计时提示

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#163]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/a13d8bb8-a4a9-4276-a055-b6bdbe531d63)

**Comment by dorislike1** [comment]
casdoor没有返回对应时间，看看后续怎么处理

**Comment by ytrjp** [comment]
casdoor没提供相应的时间，微信支付默认是2小时有效。
