### ISSUE TITLE
个人中心-用户信息应该有个会员版本展示，现在没有展示

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#164]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/2af6bd25-2ca4-494e-b866-8006c49fdda4)

**Comment by jindasong** [comment]
调用查询会员等级和起始时间接口看下是否有订阅的内容
https://apifox.com/apidoc/shared-cb7654bf-a773-4c36-94de-f1e5adb0a2c7/api-158038084

**Comment by ytrjp** [comment]
订阅API已通，当前订阅已可以正常返回
