### ISSUE TITLE
个人中心-购买会员后没有展示到期时间

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#166]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/115a0d15-5d4c-4c89-80d8-d18ee11cc885)

**Comment by ytrjp** [comment]
订阅时需要传endingat参数，需要传到期时间。比如体验版基于当前日期延后了3天
currentTime := time.Now()
	subscriptionAt := currentTime.Format(time.RFC3339)
	endingAt := currentTime.AddDate(0, 0, 3).Format(time.RFC3339)
	optSubscriptions := &payload.LagoSubscriptionsPayload{
		LagoServicePayload: payload.LagoServicePayload{
			LagoApiKey: app.SerConf.Lago.LagoApiKey,
			LagoHost:   app.SerConf.Lago.LagoUrl,
		},
		LagoSubscriptionInfo: payload.LagoSubscriptionInfo{
			ExternalCustomerId: opt.LagoCustomerInfo.ExternalId,
			PlanCode:           "trial_version",
			ExternalId:         opt.LagoCustomerInfo.ExternalId,
			BillingTime:        "anniversary",
			SubscriptionAt:     subscriptionAt,
			EndingAt:           endingAt,
		},
	}

**Comment by ytrjp** [comment]
前端支付后，调用lago订阅API，会触发webhook，webhook里会对日期进行修订（目前只有测试版本配置）
