### ISSUE TITLE
编辑页最上方展示了其他异常内容

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#171]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/93da3c7d-ae2d-4a5f-a025-dd3fd6afe3a1)

**Comment by turbo-wpc** [comment]
描述下操作路径吧，本地复现不了

**Comment by dorislike1** [comment]
看看是不是有一次合代码有问题出现的问题，如果能复现，给个复现的路径
