### ISSUE TITLE
素材库-背景批量删除后页面没有刷新内容还在展示

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#180]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/5feadd3d-9548-4b7e-af24-864e8b33ff97)

**Comment by dorislike1** [comment]
删除接口返回成功，重新拉列表时数据还在

**Comment by dorislike1** [comment]
接口看下吧

**Comment by SEfxl** [comment]
经李昂确认，接口传参有误
