### ISSUE TITLE
音色列表-选择收藏的列表时会出现两个音色为选中态【本次不改】

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#182]
![Uploading image.png…]()

**Comment by dorislike1** [comment]
房子看看这个应该怎么交互

**Comment by fangxiuq** [comment]
这个问题，本次迭代可先不修改。点击收藏列表中的音色，会出现下方音色列表中的对应的音色也被选中，其实选择的都是同一个音色。后续该功能需要改造，将我的收藏列表，融合到音色列表中
