### ISSUE TITLE
音色列表-中文模式下音色的标签应该为中文展示

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#183]
![Uploading image.png…]()

**Comment by turbo-wpc** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/31506444/dcae00c2-466f-4849-867d-d757c1c09d91)
是说这里吗？取标签的时候，怎么区分应该用哪个？

**Comment by SEfxl** [comment]
audio/timbre/enum接口返回了映射关系，且是在请求列表之前获取的，可自行映射

**Comment by SEfxl** [comment]
已经兼容
