### ISSUE TITLE
AI上传文件目前只能上传一个文件，是否应该修改文案提示一下用户

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#190]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/247148d5-61b6-4a0d-a73b-62070a00773f)

**Comment by dorislike1** [comment]
房子给个文案

**Comment by fangxiuq** [comment]
文案：请每次上传一个格式为pdf、ppt、txt、jpeg、json的文件。
