### ISSUE TITLE
个人中心-用户权益有效时长展示异常

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#206]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/cd23d885-d28a-4b95-8131-1147985f5a88)

**Comment by jindasong** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/16760633/d32a91a3-45bd-40c9-a4df-c507fc85f4d7)
服务端看下，查询会员等级和起始时间接口未返回结束时间

**Comment by jindasong** [comment]
结束时间为空时前端暂时做个兜底处理，隐藏有效期的展示
