### ISSUE TITLE
上传素材时点击页面其他位置能不能关了弹窗？【找房子老师沟通吧】

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#213]
![Uploading image.png…]()

**Comment by xuyao0916** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/79676197-5f8f-4c60-9f1d-5d5fc8ef5b6b)

**Comment by dorislike1** [comment]
放优化里吧，

**Comment by dorislike1** [comment]
点叉号关掉，关掉就取消上传

**Comment by fangxiuq** [comment]
先按照如上结论，我们下午沟通的逻辑

**Comment by xuyao0916** [comment]
点击其他位置也会关闭弹窗

**Comment by dorislike1** [comment]
shadcn都是统一的处理交互，不支持该功能
