### ISSUE TITLE
AI生成内容，背景第一个为视频时，生成完成背景加载失败

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#218]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/b047c3ef-6154-4f18-8043-8a8aa0f48abf)

**Comment by jindasong** [comment]
已修复

**Comment by dorislike1** [comment]
这个看看还有问题没，如果有问题放二期吧，这块要放后端整体在做优化
