### ISSUE TITLE
【智能生成】生成每个讲解的标题和实际文本内容，对应不起来

### ISSUE THREAD

**Issue by fangxiuq** [psyai-net/webAppbug#221]
![Uploading 20240401-164633.jpeg…]()

**Comment by moonfiendwill** [comment]
后端查看数据库数据的对上的，经验证，前端偶现点击切换卡片的时候会导致换位置，目前不知道怎么稳定复现

**Comment by moonfiendwill** [comment]
原因是 issue #309 导致
