### ISSUE TITLE
我的视频翻页-第一页和第二页的内容返回一样

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#224]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/e449e155-0f9d-472d-8a28-aac299ba9415)
![image](https://github.com/psyai-net/webAppbug/assets/103931565/962b51f6-e462-4a14-a508-140d57089421)

**Comment by ytrjp** [comment]
这个API已经安前端要求替换为从1开始，所以传0默认会是1，第2个请求传的1。所以1、2页内容相同。请前端改成默认从1开始计算

**Comment by turbo-wpc** [comment]
已修复
