### ISSUE TITLE
背景出现挤压

### ISSUE THREAD

**Issue by four2024** [psyai-net/webAppbug#232]
<img width="471" alt="image" src="https://github.com/psyai-net/webAppbug/assets/143800634/6f55ca57-ef1b-461f-a2fe-77d854dca03d">

**Comment by dorislike1** [comment]
这个定了固定大小，这个如果后期需要优化，放优化里吧

**Comment by dorislike1** [comment]
这个改后需要后端接口也得改生成视频才生效，下期可以规划下这问题

**Comment by fangxiuq** [comment]
这个问题，建议洪亮和东霞对下，看视觉上如何展示合适，前端展示定好标准
