### ISSUE TITLE
【内容编辑】录音，录音成功后，上传的音频文件，显示时长成功后，但是格式不对

### ISSUE THREAD

**Issue by fangxiuq** [psyai-net/webAppbug#235]
![Uploading screenshot-20240401-182940.png…]()

**Comment by dorislike1** [comment]
房子给个正确的格式

**Comment by fangxiuq** [comment]
如果分钟级音频，显示时长：XX:XX，如：01:30
如果小时级音频，显示时长：XX:XX:XX，如：10:25:30
