### ISSUE TITLE
个人中心-用户权益没有展示

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#240]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/bbba1da2-a0d6-49d2-95a3-cb2e22970813)

**Comment by ytrjp** [comment]
基于订阅API已调通，可以看下正常获取参数

**Comment by turbo-wpc** [comment]
已修复

**Comment by dorislike1** [comment]
4月3号新注册的用户有
