### ISSUE TITLE
编辑页-添加卡片后人物应该选择当前选择的人物而不是第一个人物

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#244]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/eb33936f-e78f-4fe8-9e1f-5b45a8a80e5e)

**Comment by turbo-wpc** [comment]
当前选择的人物是🈯️选中卡片中所选中的人物？

**Comment by wfy000** [comment]
目前以现在的为准不做修改
