### ISSUE TITLE
编辑页修改视频名称保存后无效，无法修改成功

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#245]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/a3e50074-a5ce-4b23-b8b3-33cd6b1e3f53)

**Comment by ytrjp** [comment]
保存成功了，现在是在前端刷新后生效。需要看下是否返回再取一次数据
![image](https://github.com/psyai-net/webAppbug/assets/1198711/addefd07-c7dc-4553-8ce2-bea07b25f1fc)

**Comment by turbo-wpc** [comment]
已修复
