### ISSUE TITLE
编辑页-横屏人物位置展示没有居中都在靠左侧

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#253]

**Comment by jindasong** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/16760633/2a460e37-ef90-4f5d-bd11-6b98aa82e034)

检查下人物列表接口ext字段中返回的人物默认坐标。
GET /assets/personal/list?name=&page=1&pageSize=17

**Comment by fangxiuq** [comment]
该问题需要改，将人物调整到居中位置，但优先级非最高

**Comment by dorislike1** [comment]
这个是按接口返回值展示的
