### ISSUE TITLE
竖屏人物位置基本上全身的人物形象都浮空展示

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#254]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/4947c57b-6489-4568-861d-40d0b8363298)

**Comment by jindasong** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/16760633/551a0ed3-1a95-403b-90e2-f03a364b0f15)

人物图片的源文件下面就有空隙

**Comment by dorislike1** [comment]
人物图片的源文件下面就有空隙

**Comment by fangxiuq** [comment]
该问题可以先暂时放一放
