### ISSUE TITLE
验证码获取频繁，提示文案需要修改

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#273]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/78bcd1d9-9ab6-4bd9-90b0-9e0cfdb3b72c)

**Comment by turbo-wpc** [comment]
确认下这个文案是接口给的吧？

**Comment by turbo-wpc** [comment]
错误文案是接口返回的

**Comment by SEfxl** [comment]
这个前段调用的casdoor，接口不在后端控制，需要前端针对相应的返回值去做弹窗文案提示

**Comment by dorislike1** [comment]
给个文案

**Comment by dorislike1** [comment]
如果报错没有信息  就直接提示 发送验证码失败  ？或者房子给个文案

**Comment by fangxiuq** [comment]
文案：验证码发送过于频繁，请稍后再试。

**Comment by xuyao0916** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/23920eb0-3141-432d-a586-f67ee97a8f90)
验证码h获取频繁提示错误
