### ISSUE TITLE
试听过程中切换音色后点击暂停 会直接生成新的音频

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#276]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/3c1d0bd7-35e1-4e06-aae9-006a0e061f0e)

**Comment by dorislike1** [comment]
修改成跟客户端保持一致

**Comment by turbo-wpc** [comment]
已修复

**Comment by dorislike1** [comment]
这个跟房子沟通过直接跟客户端保持一样就行 改成生成音频
