### ISSUE TITLE
消息通知展示的文本应该不太对 不是很流畅

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#286]
<img width="430" alt="image" src="https://github.com/psyai-net/webAppbug/assets/103931565/690b5877-4b88-4b66-be52-a81859d30fc6">

**Comment by dorislike1** [comment]
房子需要和后端对下

**Comment by fangxiuq** [comment]
@SEfxl 辛良看下，应该是 [提交时间]字段，未被替换成真实时间

**Comment by SEfxl** [comment]
done，已经修复
