### ISSUE TITLE
专业版立即咨询按钮-填写信息页面获取验证码按钮一直是灰色，都不知道能不能点

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#291]
<img width="1360" alt="image" src="https://github.com/psyai-net/webAppbug/assets/103931565/82188668-5553-472d-b9db-8698389dfb8e">

**Comment by dorislike1** [comment]
不要这个验证码了，具体可以问福英

**Comment by xuyao0916** [comment]
要修改当前页面，当前问题不做修改
