### ISSUE TITLE
创建production接口clip顺序反了

### ISSUE THREAD

**Issue by moonfiendwill** [psyai-net/webAppbug#309]
![img_v3_029o_4b9fa5d4-fee3-4d71-8a0a-2546a32bea7g](https://github.com/psyai-net/webAppbug/assets/104424309/80f95d21-a2b8-4a6c-9495-fb24c68ce588)

**Comment by moonfiendwill** [comment]
![img_v3_029o_6281943a-332a-435e-a62a-f9563c6e9c3g](https://github.com/psyai-net/webAppbug/assets/104424309/ddb6aaed-dca5-4586-a4e3-7a07c9b1347f)

**Comment by moonfiendwill** [comment]
最终合成的视频顺序也是反的

**Comment by ytrjp** [comment]
之前查询依据更新时间倒序，改为创建时间正序返回
