### ISSUE TITLE
合成视频时停留在我的视频页面，进度不会发生变化，刷新后才会展示最新的进度

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#312]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/8917e286-2f88-4f92-86f2-0827250b780e)

**Comment by dorislike1** [comment]
房子看看，这个要一直刷接口吗？用户又操作就能看到

**Comment by xuyao0916** [comment]
需要房子老师确认的 指给房子老师，直接找房子老师确认，指给我就是要在页面刷新的~ 这个体验太不友好了
