### ISSUE TITLE
视频名称规则是否需要修改，现在根本不知道视频名称是啥

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#313]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/063fd06b-c167-49a3-814e-40734b824a93)

**Comment by fangxiuq** [comment]
视频名称规则改为：未命名_小时分钟秒，如：未命名_162304

**Comment by dorislike1** [comment]
又改需求了，下次再随便改需求不改了，很费时间
