### ISSUE TITLE
我的视频-点击创建副本提示名称超过最大字数限制

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#315]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/a6d23a0d-5f5b-4cb5-a10f-048dc432ed4f)

**Comment by dorislike1** [comment]
点击创建副本提示名称超过最大字数限制 ,然后那怎么了

**Comment by ytrjp** [comment]
已发布到开发环境
