### ISSUE TITLE
页面停留在首页会出现自动调用接口，以下截图

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#323]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/4467acd0-d136-4d7e-89a4-8b350c32fb02)

**Comment by dorislike1** [comment]
这个是为进编辑页做准备的接口

**Comment by xuyao0916** [comment]
点击新建这些需要的接口还会重新被调用一遍。
![image](https://github.com/psyai-net/webAppbug/assets/103931565/15bae4ed-3324-4c87-8763-843e220c6ac3)
回收站、中文、视频接口这个和新建没有关系吧
