### ISSUE TITLE
个人中心的视频消耗时长，展示错误

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#343]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/94f5e4fb-c216-479e-a992-651c57a86aa7)

**Comment by ytrjp** [comment]
都按毫秒为单位计算

**Comment by xuyao0916** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/3901ab6e-c778-4c95-80e8-d5d4e7948a9f)
算的还是还是错的
