### ISSUE TITLE
我的视频进入多卡片的视频编辑页，进入后未加载完成直接点击合成报错

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#345]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/eb8f3c7e-5230-49e2-bac5-9ef0293b6857)

**Comment by xuyao0916** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/ebad7e47-0206-4c41-9fe8-e43410c3b5f8)

**Comment by dorislike1** [comment]
重复bug 鹏哥已经在看不匹配的问题
