### ISSUE TITLE
进入编辑页-接口重定向失败，内容无法加载

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#347]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/9f90bc16-ef2a-416a-b20b-59c3108a5e89)

**Comment by dorislike1** [comment]
切页面是正常的

**Comment by xuyao0916** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/4497637e-8d20-402c-96ee-5e0f514360e7)
