### ISSUE TITLE
上传背景的提示文案是错误的，图片和视频不能一起

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#35]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/88ef1b11-93da-4a32-a910-605874b7d3cf)

**Comment by dorislike1** [comment]
产品提供下文案

**Comment by xuyao0916** [comment]
去看UI图，有文案

**Comment by dorislike1** [comment]
你复制过来也行，我看见有编辑页的，没有素材页的呀

**Comment by xuyao0916** [comment]
请上传10个以下，图片单个大小不超过20MB的png、jpg、jpeg，视频单个大小不超过600MB的mp4、avi、wma文件
推荐尺寸：1920*1080（横版）、1080*1920（竖版）

**Comment by turbo-wpc** [comment]
已修复
