### ISSUE TITLE
编辑页-背景图片删除后，进入编辑页背景还存在并使用了

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#353]

**Comment by dorislike1** [comment]
你需要抓接口的返回值，在我这没有复现过

**Comment by dorislike1** [comment]
// With SSR, we usually want to set some default staleTime
// above 0 to avoid refetching immediately on the client

**Comment by xuyao0916** [comment]
选择视频背景后删除视频，返回首页在新建进入还是这个视频背景
