### ISSUE TITLE
lago服务不稳定，经常挂掉需要重启才可以正常使用

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#373]

**Comment by ytrjp** [comment]
已经从1.0.0升级到1.2.0版本，后续继续看下稳定性

**Comment by xuyao0916** [comment]
还是不稳定，又挂了，数据都没了

**Comment by ytrjp** [comment]
原因是多个SAE服务需要共享一个存储路径作为缓存。辛良和明浩尝试了两种方式：
1. 基于ECS将Lago服务部署在同一台机器下，跟开发环境保持一致。可以正常运行
2. 基于多SAE环境配置共享存储OSS地址，测试后发现Lago-api服务不稳定

Lago基于ECS环境进行部署使用
