### ISSUE TITLE
批量上传upload时失败，提示内容异常

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#400]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/aa707f6e-ed54-4ea8-bd49-c015160ad9f1)
![image](https://github.com/psyai-net/webAppbug/assets/103931565/fcce82b1-424c-47f3-b3b7-a22d27c53055)

**Comment by fangxiuq** [comment]
抱歉，您的批量上传遇到了问题。请检查您的图片是否满足以下要求：
（1）图片，单个大小不超过20MB的png、jpg、jpeg文件；
（2）视频，单个大小不超过600MB的mp4、avi、wmv文件；
（3）总体上传数量不超过10张图片；
符合以上条件后，请尝试重新上传。如有任何疑问，请联系我们的客户服务团队。感谢您的理解与支持。

**Comment by dorislike1** [comment]
这么多文字怎么提示？ toast的话还没看清就没了

**Comment by wfy000** [comment]
您的批量上传失败，请确保上传文件的格式和单个大小正确，且总数不超过10张
