### ISSUE TITLE
AI生成模块，上传文件失败后是不是应该给个重新上传按钮

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#402]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/765ffdec-4b8a-4162-9090-12a50f268d93)

**Comment by four2024** [comment]
<img width="860" alt="image" src="https://github.com/psyai-net/webAppbug/assets/143800634/a7daac87-22ed-436e-ade2-f5807865b00a">
