### ISSUE TITLE
重复购买年份会员的处理逻辑

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#410]

**Comment by fangxiuq** [comment]
之前产品的PRD：https://uvetjcpbqd.feishu.cn/wiki/YWNmwi5DKiul7jkttEkchlZhnsh

目前线上逻辑如下：

相同权益，比如多个月，扣ending_at最近时间的plan;
不同权益，比如有年、月，扣最大的，年会员plan；
因此：企业版权益> 年会员 > 月会员 > 体验版
当权益相同的时候按照最近时间扣除和展示（可最大保障用户权益，比如两个年会员，年A,3月份过期  年B 4月份过期，则优先扣除年A）【当前我们暂未进行多个权益相同的plan配置，线上已经配置，可拓展】

符合要求；

**Comment by fangxiuq** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/35586227/f1e4bb9b-343a-4a9b-b38a-fd1f8c3284a8)
