### ISSUE TITLE
编辑页面：录音当前为可用状态，UI显示错误（图标显示的不可用状态），另外上传和录音模块边框颜色不一致

### ISSUE THREAD

**Issue by four2024** [psyai-net/webAppbug#441]
<img width="336" alt="image" src="https://github.com/psyai-net/webAppbug/assets/143800634/dcc8fa09-9843-485b-9eae-4eae86c8fa1c">

**Comment by dorislike1** [comment]
等figama开通会员后统一换下不对的图标
