### ISSUE TITLE
背景使用有声音的背景时合成时，播放内容会出现背景视频声音（下载完成后也有背景声音）

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#445]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/aa16023e-80d5-4876-bb28-456752dbe3b8)

**Comment by dorislike1** [comment]
下载完成后也有背景声音有声音需要后端看看

**Comment by KyleCe** [comment]
已发布  2024-05-15 14:44:56
