### ISSUE TITLE
手机验证码登录时提示文案不太合理

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#449]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/960decdd-537c-488f-a46a-29117e4c0980)

**Comment by xuyao0916** [comment]
phone - 验证码未发送！

**Comment by wfy000** [comment]
提示文案：“验证码未发送，请点击“发送验证码”后重试”

**Comment by xuyao0916** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/4b9772b6-5405-453b-8a45-12b171f8baa3)

**Comment by Laura-41** [comment]
提示文案：“密码错误，您还有xx次尝试的机会”
