### ISSUE TITLE
二次编辑-添加卡片后删除第一个视频，返回出现db error

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#457]

**Comment by ytrjp** [comment]
返回的数据不正确，已删除的数据，也返回到了后端。当前后端已对更新的数据做了保护处理，先查询再更新，没有查询到的数据不再更新，不会报db error。
需要前端进一步处理，返回正确的数据。

**Comment by dorislike1** [comment]
等undo redo一起做
