### ISSUE TITLE
下载后的视频，图层和在webapp中的不一致

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#464]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/d58b1c69-29e2-498b-90bd-4191b78e465d)

**Comment by KyleCe** [comment]
/video/instant_vid

生成视频API中添加虚拟人层级参数：
z_index (声明后，与素材内容混编，index即数组下标）

<img width="1210" alt="image" src="https://github.com/psyai-net/webAppbug/assets/8437760/3631d6cf-69ee-43af-98f2-d1803b5a25d6">

**Comment by KyleCe** [comment]
变更已发布线上
