### ISSUE TITLE
mac电脑登录时，手机号框内图标会带到输入验证码框内

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#478]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/f822785e-7512-47d0-8e8b-592f4b5aaefd)

**Comment by dorislike1** [comment]
他把自己安装的浏览器插件都禁用下 项目里都没有这个标

**Comment by dorislike1** [comment]
这是电脑插件，这个浏览器的所有网站都这样
