### ISSUE TITLE
我的视频，背景是视频时，合成中的视频卡片背景是黑色；

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#484]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/ee0fdef2-e26f-47eb-8eaa-83938f51df25)

**Comment by xuyao0916** [comment]
找房子老师确认

**Comment by dorislike1** [comment]
这个等仓库确认好了修改，

**Comment by dorislike1** [comment]
再新重建就可以了
