### ISSUE TITLE
个人中心，我的账户中，账号应该显示的手机号；

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#485]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/bce90ea3-1a86-4873-b0be-986a6f720f68)

**Comment by SEfxl** [comment]
已经新增

**Comment by xuyao0916** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/9c4f9276-a67f-473c-ae3a-dcb2f979e994)
接口已经新增了phone字段
