### ISSUE TITLE
合成中的视频卡片，也应该是个正常的卡片，有菜单，有“取消”，“删除”等操作：

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#498]

**Comment by xuyao0916** [comment]
右上角增加功能栏按钮，展示删除，卡片封面展示取消按钮

**Comment by KyleCe** [comment]
cancel功能 待提供，开发中；

**Comment by KyleCe** [comment]
cancel功能已开完、

**Comment by KyleCe** [comment]
已开发完成

**Comment by KyleCe** [comment]
![img_v3_02ar_4c733281-fca4-4f2b-8857-481325401c0g](https://github.com/psyai-net/webAppbug/assets/8437760/3563b10f-6219-4993-9ce4-124cbc49fe47)

**Comment by KyleCe** [comment]
已发布

**Comment by fangxiuq** [comment]
合成中的视频卡片，鼠标放到卡片上hover状态下：
1.卡片上展示【取消】按钮，可取消视频合成任务；
2.右上角出现【...】按钮，点击该按钮后，出现“删除”下拉按钮；

辛苦 @four2024 给下视觉；
