### ISSUE TITLE
编辑页-上传背景文案提示错误

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#50]
![Uploading image.png…]()

**Comment by dorislike1** [comment]
接口看下

**Comment by xuyao0916** [comment]
就是一个UI提示文案，需要看什么接口？

**Comment by dorislike1** [comment]
你附的图片加载不出来，说的是这里的文案吗？
![image](https://github.com/psyai-net/webAppbug/assets/15520616/85f1fb9a-592d-4d9c-a7a7-9f8077b3d011)

**Comment by xuyao0916** [comment]
对文案还是不对，你看下UI

**Comment by dorislike1** [comment]
文案又从设计图上复制了一遍过来

**Comment by xuyao0916** [comment]
请上传10个以下，图片单个大小不超过20MB的png、jpg、jpeg，视频单个大小不超过600MB的mp4、avi、wma文件
推荐尺寸：1920*1080（横版）、1080*1920（竖版）

**Comment by turbo-wpc** [comment]
已修复
