### ISSUE TITLE
背景缩略图展示未撑满整个卡片

### ISSUE THREAD

**Issue by four2024** [psyai-net/webAppbug#503]
<img width="329" alt="image" src="https://github.com/psyai-net/webAppbug/assets/143800634/5c6847b7-0b23-4aef-8c5c-56aeb0414e4e">

**Comment by york0psyai** [comment]
![img_v3_02c8_80d77935-8806-4d7c-848c-44dedea999fg](https://github.com/psyai-net/webAppbug/assets/170386254/942c0bbe-7401-4c28-a355-7ede1bbbd8c4)
和洪亮哥沟通，按上图调整 @four2024
