### ISSUE TITLE
存储空间的进度条可以超过最长限制

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#508]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/f0c6372b-89a3-4e87-adf5-f75cfb0be220)

**Comment by four2024** [comment]
<img width="1381" alt="image" src="https://github.com/psyai-net/webAppbug/assets/143800634/71299540-262a-49b5-a82e-4a72c17d0d46">
