### ISSUE TITLE
账号密码登录，提示内容需要找产品确认一下

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#54]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/05e06cf9-181e-4c5c-b610-cbd6d692e6e9)

**Comment by dorislike1** [comment]
房子看看这个文案需要改吗？改成什么

**Comment by jindasong** [comment]
现在文案内容是 casdoor 登录接口返回的提示信息
