### ISSUE TITLE
首页-上传url、文件字体验证不太一样

### ISSUE THREAD

**Issue by xuyao0916** [psyai-net/webAppbug#57]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/9191d536-9ab3-42fa-81c9-7f3c7da39acf)

**Comment by jindasong** [comment]
无法复现，页面刷新后是否正常？

**Comment by dorislike1** [comment]
什么意思，应该是什么样

**Comment by xuyao0916** [comment]
![image](https://github.com/psyai-net/webAppbug/assets/103931565/c05220dd-8006-4ee8-8aa4-f8ca56cecfae)
l两个字体明显不一样的啊
